import{a as v,i as f,S}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();function P(e){return`<li class="gallery-item">
  <a class="gallery-link" href="${e.largeImageURL}">
    <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
  </a>
   <div class="image-details">
                    <p>Likes: ${e.likes}</p>
                    <p>Views: ${e.views}</p>
                    <p>Comments: ${e.comments}</p>
                    <p>Downloads: ${e.downloads}</p>
                </div>
</li>`}function q(e){return e.map(P).join("")}async function g(e,r){const i="https://pixabay.com",c="/api/",o={key:"42305658-75508782eac06a666c1fb928b",image_type:"photo",orientation:"horizontal",safesearch:"true",q:e,per_page:15,page:r},s=`${i}${c}?${new URLSearchParams(o)}`;return(await v.get(s)).data}const $=document.querySelector(".js-search-form"),u=document.querySelector(".gallery"),h=document.querySelector(".js-loader"),p=document.querySelector(".js-btn-load"),l=document.querySelector(".load-message");let a,n,m;$.addEventListener("submit",E);p.addEventListener("click",I);async function E(e){if(e.preventDefault(),a=e.target.elements.search.value.trim(),n=1,!a){d("Sorry, there are no images matching your search query. Please try again!");return}l.classList.remove("hidden"),L();try{const r=await g(a,n);if(r.totalHits===0){d("There was a problem with the fetch operation. Please try again later.");return}m=Math.ceil(r.totalHits/15),u.innerHTML="",y(r.hits),l.classList.add("hidden")}catch(r){d(r),m=0,u.innerHTML=""}w(),b(),e.target.reset()}async function I(){if(n+=1,!a)return f.warning({title:"Warning",message:"Please enter a search query",position:"topCenter"});l.classList.remove("hidden"),L();const e=await g(a,n);y(e.hits),w();const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"}),l.classList.add("hidden"),b()}function y(e){const r=q(e);u.insertAdjacentHTML("beforeend",r),new S(".gallery a").refresh()}function M(){p.classList.remove("hidden")}function T(){p.classList.add("hidden")}function L(){h.classList.remove("hidden")}function w(){h.classList.add("hidden")}function b(){n>=m?(T(),f.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topCenter"})):M()}function d(e){f.error({title:"Error",message:e,position:"topCenter"})}
//# sourceMappingURL=commonHelpers.js.map
